appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VxfJPXPwOB64hUphA3VtQkPA9arr7DAzUTtGJ8cXkrYZ/FOrfROYLX+uJaWFo57KnleJxzGwqf1HmRWoYSXy/E2kKm0UeS4R41kyU6LnH56WB/AV1Z2wK4RwrElK5cc8uZ34oNWL8D+bcesLKzdYVDyRt2n5qhvUTzNENBEuw2+ObmycvGl2lFgXK43dqImAu0l06FqACARRz9YKXihG/AgG77IUfEamsLqecF06e2r3C9n5WJCBs2AbkDqcJexyXMY6oKg3ZCfAmgp0B0BD/esgu9hDsPEgiAENojHmF5ELdVIHB3Ty+OL9RkMCH4CYL7idj+ztIkDRNcLL8U3vV9VtfkPYBpWNfntjcRHAL9pknXA0hqOg+kkxgjeacwSxhtOnGbd1RlVxX9O4Tr2k5lVva2WRnjHj/OeZ5dakhgVQz3TXHYjQgrfm7Wn0tKGiOmnhmVEQ0XN8h9LdAmnKIFrGRz1FPQjh16l4Qfcwpnt5c/ajQ6qKYxyDG7t+/6VHyECQwGGsYxOpdlE7ahHORKPaek7mTmReoaqPCLhjONoiOYh/h/DYi0Svwnqk4hkiKRKFIOOAWSzBNseCLH6kpAWP1eHdVQEzCMlw781iGKy9nsMgfXYDLOVhDH83/zhzrLrwPkTGQNvnv+zNx9dQNwc12dn686zZJytsXI6LLis=}
